apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: gcr.io/predictive-guru-425117-r4/api-service:
          ports:
            - containerPort: 8765
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  ports:
    - port: 8765
      targetPort: 8765
  selector:
    app: api-service

#  docker build --tag gcr.io/predictive-guru-425117-r4/api-service:1.1 ./api-gateway
#  docker push gcr.io/predictive-guru-425117-r4/api-service:1.1
#  kubectl apply -f ./k8s/api-deployment.yml