apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract-service
  template:
    metadata:
      labels:
        app: contract-service
    spec:
      containers:
        - name: contract-service
          image: gcr.io/predictive-guru-425117-r4/contract-service:1
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: contract-service
spec:
  type: LoadBalancer
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: contract-service


#  docker build --tag gcr.io/predictive-guru-425117-r4/contract-service:1 ./Contrat-Service
#  docker push gcr.io/predictive-guru-425117-r4/contract-service:1
#  kubectl apply -f k8s/contract-deployment.yml