apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: gcr.io/predictive-guru-425117-r4/eureka-service:1
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: LoadBalancer
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka-server


#  docker build --tag gcr.io/predictive-guru-425117-r4/eureka-service:1 .
#  docker push gcr.io/predictive-guru-425117-r4/eureka-service:1
#  kubectl apply -f api-deployment.yml